In [1]:
import numpy as np
from numpy import *
from numpy import random # random data
import csv
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
from itertools import chain
import nltk
nltk.download('punkt')
import codecs
import string
from nltk.corpus import stopwords
import re
import pprint
import random
from urllib import request
from nltk import word_tokenize
from nltk.corpus import brown
from nltk.corpus import wordnet as wn

from nltk.stem import SnowballStemmer
snowball_stemmer = SnowballStemmer("english")
from nltk.stem import PorterStemmer
from nltk.stem.wordnet import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\schap\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
import gensim
# the model is organized like this: word = embeddings
small_model = gensim.models.KeyedVectors.load_word2vec_format('/Users/schap/Desktop/Text Analysis/small-embeddings.txt', binary=False)

In [17]:
exclude = set(string.punctuation)
stop_word_list = stopwords.words('english')

# input should be a string - we need a simple pipeline for getting word embeddings
def nlp_simple_pipeline(text):
    
    text = str(text)
    
    #it depends if the words have been lowercased or not
    text = text.lower()
    
    text = nltk.word_tokenize(text)
        
    text = [token for token in text if token not in exclude and token.isalpha()]
    
    text = [token for token in text if token not in stop_word_list]

    return text

In [19]:
def article_embedding(cleaned_article):
    
    article_embedd = []
    # for each word in the article, you take the embeddings
    for word in cleaned_article:
        try:
            embed_word = small_model[word]
            article_embedd.append(embed_word)
        except KeyError as e:
            print (e,word)
            continue
    
    # average vectors of all words
    avg = [float(sum(col))/len(col) for col in zip(*article_embedd)]
    avg = np.array(avg).reshape(1, -1)
    return avg

In [11]:
#d4april211992 is the political parties decision used to make dictionaries
politicalparties = codecs.open("/Users/schap/Desktop/TA_Data/AC/1992/TXT_Files/D4.Apr21.1992.MAJ.txt", "r").read().strip().split('\n')


In [14]:
#pp = str(politicalparties) - can add this straight into the cleaning pipeline 

In [21]:
cleaned_politicalparties = nlp_simple_pipeline(politicalparties)

In [22]:
article_embedding(cleaned_politicalparties) #this is the average word embedding array for the political parties decision 

"word 'manov' not in vocabulary" manov
"word 'hadjistoychev' not in vocabulary" hadjistoychev
"word 'nenovski' not in vocabulary" nenovski
"word 'chipev' not in vocabulary" chipev
"word 'kornezov' not in vocabulary" kornezov
"word 'pencho' not in vocabulary" pencho
"word 'arabadjiev' not in vocabulary" arabadjiev
"word 'zks' not in vocabulary" zks
"word 'podks' not in vocabulary" podks
"word 'zks' not in vocabulary" zks
"word 'zks' not in vocabulary" zks
"word 'zinposk' not in vocabulary" zinposk
"word 'podks' not in vocabulary" podks
"word 'zinposk' not in vocabulary" zinposk
"word 'elico' not in vocabulary" elico


array([[-0.05963646,  0.07555592, -0.26189992,  0.02443251,  0.24358592,
         0.23766842,  0.04411118, -0.1823    , -0.0370389 , -0.09321212,
         0.06896044, -0.10994865, -0.05339678, -0.04009624,  0.12137559,
         0.04138564,  0.03972388, -0.30445184,  0.24392719, -0.14349354,
         0.09929708, -0.0056753 , -0.02012062, -0.02708822, -0.06955654,
        -1.14164018, -0.24864049, -0.32142994, -0.04126756,  0.19839959,
         2.50127475, -0.06098029, -0.61746289, -0.58962909, -0.1814652 ,
        -0.153964  ,  0.11875747, -0.08844476, -0.33940533,  0.06734334,
        -0.1609698 , -0.16733732,  0.10245137,  0.25683143, -0.40078244,
         0.09947696, -0.32919419,  0.3308041 ,  0.05733062, -0.15416452]])

In [23]:
avg_pp = article_embedding(cleaned_politicalparties)

"word 'manov' not in vocabulary" manov
"word 'hadjistoychev' not in vocabulary" hadjistoychev
"word 'nenovski' not in vocabulary" nenovski
"word 'chipev' not in vocabulary" chipev
"word 'kornezov' not in vocabulary" kornezov
"word 'pencho' not in vocabulary" pencho
"word 'arabadjiev' not in vocabulary" arabadjiev
"word 'zks' not in vocabulary" zks
"word 'podks' not in vocabulary" podks
"word 'zks' not in vocabulary" zks
"word 'zks' not in vocabulary" zks
"word 'zinposk' not in vocabulary" zinposk
"word 'podks' not in vocabulary" podks
"word 'zinposk' not in vocabulary" zinposk
"word 'elico' not in vocabulary" elico


In [25]:
#varna free university case D17.Nov24.1992.MAJ 
varnafreeuniversity = codecs.open("/Users/schap/Desktop/TA_Data/AC/1992/TXT_Files/D17.Nov24.1992.MAJ.txt", "r").read().strip().split('\n')
cleaned_vfu = nlp_simple_pipeline(varnafreeuniversity)
avg_vfu = article_embedding(cleaned_vfu)

"word 'manov' not in vocabulary" manov
"word 'nenovski' not in vocabulary" nenovski
"word 'chipev' not in vocabulary" chipev
"word 'zhabinska' not in vocabulary" zhabinska
"word 'kornezov' not in vocabulary" kornezov
"word 'pencho' not in vocabulary" pencho
"word 'zvo' not in vocabulary" zvo
"word 'zvo' not in vocabulary" zvo
"word 'zvo' not in vocabulary" zvo


In [28]:
#D5.April6.1993.MAJ, civil service case 
civilservice =  codecs.open("/Users/schap/Desktop/TA_Data/AC/1993/TXT_Files/D5.Apr6.1993.MAJ.txt", "r").read().strip().split('\n')
cleaned_cs = nlp_simple_pipeline(civilservice)
avg_cs = article_embedding(cleaned_cs)

"word 'manov' not in vocabulary" manov
"word 'hadjistoychev' not in vocabulary" hadjistoychev
"word 'nenovski' not in vocabulary" nenovski
"word 'chipev' not in vocabulary" chipev
"word 'zhabinska' not in vocabulary" zhabinska
"word 'kornezov' not in vocabulary" kornezov
"word 'pencho' not in vocabulary" pencho
"word 'arabadjiev' not in vocabulary" arabadjiev


In [27]:
from sklearn.metrics.pairwise import cosine_similarity

# Cosine Similarity Between the 'Political' Cases used to make dictionaries

In [30]:
print("compare political parties case and varna free university case",cosine_similarity(avg_pp, avg_vfu))
print("compare political parties case and civil service case",cosine_similarity(avg_pp, avg_cs))
print("compare political parties case and political parties case", cosine_similarity(avg_pp, avg_pp)) #for control

compare political parties case and varna free university case [[0.97956879]]
compare political parties case and civil service case [[0.98109455]]
compare political parties case and political parties case [[1.]]


## code to get avg embedding for appropriations cases

In [ ]:
#this is a state budget case D11.July17.1995.MAJ.txt 

In [31]:
statebudget =  codecs.open("/Users/schap/Desktop/TA_Data/AC/1995/TXT_Files/D11.July17.1995.MAJ.txt", "r").read().strip().split('\n')
cleaned_sb = nlp_simple_pipeline(statebudget)
avg_sb = article_embedding(cleaned_sb)

"word 'manov' not in vocabulary" manov
"word 'hadzhistoychev' not in vocabulary" hadzhistoychev
"word 'pencho' not in vocabulary" pencho
"word 'arabadjiev' not in vocabulary" arabadjiev
"word 'pzrzdbrb' not in vocabulary" pzrzdbrb
"word 'lsidb' not in vocabulary" lsidb
"word 'pzrzdbrb' not in vocabulary" pzrzdbrb
"word 'pzrzdbrb' not in vocabulary" pzrzdbrb
"word 'pzrzdbrb' not in vocabulary" pzrzdbrb


# Cosine Similarity between Political Cases and Appropriations

In [32]:
print("compare state budget case and varna free university case",cosine_similarity(avg_sb, avg_vfu))
print("compare state budget case and civil service case",cosine_similarity(avg_sb, avg_cs))
print("compare state budget case and political parties case", cosine_similarity(avg_sb, avg_pp))

compare state budget case and varna free university case [[0.96692886]]
compare state budget case and civil service case [[0.97694753]]
compare state budget case and political parties case [[0.95378009]]


## Code to get avg embedding for random case

this is a random case I chose D4.Feb27.1996.MAJ.txt, this is the summary on the spreadsheet: unconstitutionality of the provisions of Article 90 of the Succession Act in so far as it is provided that testament , drawn up after inclusion in the labor co farms or other entities based on these agricultural organizations of cooperative property , the ownership of which is recovered in Art 0.10 , paragraph 1 OUFLA no effect on these properties

In [33]:
randomcase =  codecs.open("/Users/schap/Desktop/TA_Data/AC/1996/TXT_Files/D4.Feb27.1996.MAJ.txt", "r").read().strip().split('\n')
cleaned_rc = nlp_simple_pipeline(randomcase)
avg_rc = article_embedding(cleaned_rc)

"word 'manov' not in vocabulary" manov
"word 'gochev' not in vocabulary" gochev
"word 'pencho' not in vocabulary" pencho
"word 'arabadjiev' not in vocabulary" arabadjiev
"word 'zspzz' not in vocabulary" zspzz


# Cosine Similarity between Political Cases and Random Case

In [34]:
print("compare random case and varna free university case",cosine_similarity(avg_rc, avg_vfu))
print("compare random case and civil service case",cosine_similarity(avg_rc, avg_cs))
print("compare random case and political parties case", cosine_similarity(avg_rc, avg_pp))

compare random case and varna free university case [[0.96036799]]
compare random case and civil service case [[0.97574694]]
compare random case and political parties case [[0.96696996]]


# Similarities using the dictionaries we created

In [36]:
dict_legal = "admissible admission allegation argument authorized compatible condition convention dispute eligible establish establishment exact facts hypothesis inadmissible incompatible ineligible jurisdiction literal mandatory norm obligation opinion precise prerequisite regulation request requirement right rules text threshold unauthorized consistent registered status prohibit purpose violation facts protective norm function interpretation illegal rejected ruling legal sense competence sanction inviolable meaning guarantee protection proof definition factual authority strict regulation regulating instructions law contradiction obligation objective formal procedure compliance principle legislation application objectively justified violation merit argument right binding rules jurisdiction must not be ruled that restrictions dismissed amendment inadmissible mandatory incompatible procedure pursuant adopted procedural appeals interpretation obligation"

In [37]:
dict_political = "democracy democratization legislature minority movement organization party policy public public opinion rallies security sympathizer platform opposition totalitarian political party ethnic religious social political will exposing exposure objectified political activity ban minority Turkish gross exhaustive separate powers separation of powers nature intimate atheist community nature believers tolerance respect natural absolutely policy vote of no confidence suffrage legislative exercised legitimate interests fundamental equal footing candidate citizenship agricultural property land owner community borders equivalent quality"

In [38]:
dict_fuzzy = "community comparison conscience cultural depend discretion ethnic history/historical ideas identity inherent integrity intent interest language natural pluralism power racial religious respect scope tolerance unity values virtues clear not clear literally contradiction substantiate decisively incidentally conformity implications satisfied occupy participation disputes right remedies composition constitutional illegitimate legitimate"

In [39]:
#legal dictionary
cleaned_legal = nlp_simple_pipeline(dict_legal)
avg_legal = article_embedding(cleaned_legal)

In [40]:
avg_legal

array([[-7.18270078e-02, -1.59617881e-01, -3.87207810e-01,
        -8.38264640e-02,  2.67771079e-01,  3.72125742e-01,
         4.68732094e-01, -1.21758422e-01,  2.43442166e-01,
         5.42849959e-02,  1.30196357e-01,  1.57843697e-01,
         3.09000453e-03, -8.46117273e-02,  2.32085111e-01,
         2.88365481e-01,  1.38392290e-02, -4.96056304e-01,
         4.82142974e-01, -3.10120738e-01,  6.94239140e-02,
        -1.68876672e-02, -1.26274518e-01, -1.31065437e-01,
        -5.27677001e-02, -1.19293228e+00, -9.86811579e-02,
        -1.08205766e-01,  2.27524076e-01,  4.19432095e-02,
         2.03335182e+00, -2.63194123e-01, -6.69654690e-01,
        -6.94595648e-01, -1.93440123e-02, -2.70860049e-01,
         5.27555544e-01, -7.17995994e-02, -4.86071373e-01,
        -7.44549444e-04, -3.58952114e-02, -3.16724213e-01,
         3.63990511e-01,  7.88958024e-01, -6.57577826e-01,
        -1.19113397e-01, -1.45032260e-01,  7.48863609e-01,
         1.42269417e-01,  8.30818682e-02]])

In [41]:
#Political dictionary
cleaned_political = nlp_simple_pipeline(dict_political)
avg_political = article_embedding(cleaned_political); avg_political

array([[-0.11953709,  0.05420678, -0.20785398, -0.08743941,  0.34572915,
         0.29418261,  0.12296292, -0.21835211, -0.04204533,  0.03117485,
        -0.00417937, -0.24578369,  0.02608949, -0.00427193, -0.11021629,
         0.03053114,  0.3046259 , -0.18534122,  0.43205037, -0.08084323,
         0.03328799,  0.13401031, -0.12612778, -0.07623116,  0.03844325,
        -1.23075059, -0.18657265, -0.3294547 ,  0.0568722 ,  0.42667425,
         2.49945921,  0.11909346, -0.53147731, -0.73542971, -0.56057767,
        -0.20849211, -0.27176004, -0.13735005, -0.37569105,  0.00844488,
        -0.30971925, -0.17473492, -0.00278664,  0.38098955, -0.27360044,
        -0.0825947 , -0.57514505,  0.2684467 ,  0.08336806, -0.14295076]])

In [43]:
#Fuzzy dictionary 
cleaned_fuzzy = nlp_simple_pipeline(dict_fuzzy)
avg_fuzzy = article_embedding(cleaned_fuzzy); avg_fuzzy

array([[-0.04680708,  0.14605288, -0.41813928, -0.15217866,  0.46915206,
         0.39624344,  0.42039832, -0.22453315, -0.05185192,  0.26039405,
         0.09915356,  0.06710168, -0.05541659, -0.32365808, -0.08253275,
         0.18629274,  0.28473247, -0.28826787,  0.54283849, -0.28615345,
        -0.12416853,  0.21966254, -0.11503318, -0.12926249,  0.29291361,
        -1.01207412, -0.44934043, -0.16432563,  0.37128305,  0.18994216,
         2.15768953,  0.18877491, -0.45327694, -0.84345636, -0.3301979 ,
        -0.20082849, -0.26797045, -0.17359209, -0.40662254,  0.09974241,
        -0.10734608, -0.28242046,  0.09693564,  0.50589189, -0.3994845 ,
         0.10272779, -0.22806295,  0.52636658,  0.04563072, -0.27062884]])

# Cosine Similarities Between Dictionaries

In [44]:
print("compare legal and political dictionaries",cosine_similarity(avg_legal, avg_political))
print("compare legal and fuzzy dictionaries",cosine_similarity(avg_legal, avg_fuzzy))
print("compare political and fuzzy dictionaries", cosine_similarity(avg_political, avg_fuzzy))

compare legal and political dictionaries [[0.83745793]]
compare legal and fuzzy dictionaries [[0.87948744]]
compare political and fuzzy dictionaries [[0.93160387]]


## Salient case versus all three dictionaries

### Political Parties

In [45]:
print("compare political parties case and legal dictionary",cosine_similarity(avg_pp, avg_legal))
print("compare political parties case and political dictionary",cosine_similarity(avg_pp, avg_political))
print("compare political parties case and fuzzy dictionary",cosine_similarity(avg_pp, avg_fuzzy))

compare political parties case and legal dictionary [[0.89598984]]
compare political parties case and political dictionary [[0.95790732]]
compare political parties case and fuzzy dictionary [[0.90704803]]


### Varna Free University

In [46]:
print("compare varna free university case and legal dictionary",cosine_similarity(avg_vfu, avg_legal))
print("compare varna free university case and political dictionary",cosine_similarity(avg_vfu, avg_political))
print("compare varna free university case and fuzzy dictionary",cosine_similarity(avg_vfu, avg_fuzzy))

compare varna free university case and legal dictionary [[0.88282023]]
compare varna free university case and political dictionary [[0.91311632]]
compare varna free university case and fuzzy dictionary [[0.84531423]]


### Civil Service

In [47]:
print("compare civil service case and legal dictionary",cosine_similarity(avg_cs, avg_legal))
print("compare civil service case and political dictionary",cosine_similarity(avg_cs, avg_political))
print("compare civil service case and fuzzy dictionary",cosine_similarity(avg_cs, avg_fuzzy))

compare civil service case and legal dictionary [[0.88452053]]
compare civil service case and political dictionary [[0.92541129]]
compare civil service case and fuzzy dictionary [[0.86632882]]


## Appropriations case versus all three dictionaries

In [48]:
print("compare state budget case and legal dictionary",cosine_similarity(avg_sb, avg_legal))
print("compare state budget case and political dictionary",cosine_similarity(avg_sb, avg_political))
print("compare state budget case and fuzzy dictionary",cosine_similarity(avg_sb, avg_fuzzy))

compare state budget case and legal dictionary [[0.85494213]]
compare state budget case and political dictionary [[0.89596775]]
compare state budget case and fuzzy dictionary [[0.81325074]]


## Random case versus all three dictionaries

In [49]:
print("compare random case and legal dictionary",cosine_similarity(avg_rc, avg_legal))
print("compare random case and political dictionary",cosine_similarity(avg_rc, avg_political))
print("compare random case and fuzzy dictionary",cosine_similarity(avg_rc, avg_fuzzy))

compare random case and legal dictionary [[0.89420073]]
compare random case and political dictionary [[0.91060002]]
compare random case and fuzzy dictionary [[0.8681557]]
